=== BISONNL/KV5/xsd/kv5-msg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright: Dit document is eigendom van Platform BISON onder Samenwerkingsverband DOVA, -->
<!--                   wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl,   -->
<!--                   zie http://creativecommons.org/licences/by-nd/3.0/nl                  -->
<!-- Opmerking: XSD is gebaseerd op TMI8 koppelvlak 5 versie 8.1.1                           -->
<!-- Version:      8.1.1a (januari 2020)                                                     -->
<!-- History:                                                                                -->
<!--          0.1: initiele versie                                                           -->
<!--          0.2: opmerkingen BISON werkgroep verwerkt                                      -->
<!--     8.1.1a: Copyright aangepast.                                                        -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv5/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv5/core" targetNamespace="http://bison.connekt.nl/tmi8/kv5/msg" elementFormDefault="qualified">
	<xs:import namespace="http://bison.connekt.nl/tmi8/kv5/core" schemaLocation="kv5-core.xsd"/>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- TMI KV5 Dynamic Station messages                                                  -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:element name="DS_TM_PUSH">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
				<xs:element name="KV5allocInfo" type="tmi8:KV5allocInfoType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DS_TM_REQ">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DS_TM_RES">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties" minOccurs="0"/>
				<xs:element name="ResponseCode" type="tmi8:ResponseCodeType"/>
				<xs:element name="ResponseError" type="tmi8:ResponseErrorType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Dossiers: KV5 allocation info message                                             -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="KV5allocInfoType">
		<xs:sequence>
			<xs:element name="passage" type="tmi8:PassageType"/>
			<xs:element name="allocation" type="tmi8:AllocationType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PassageType">
		<xs:sequence>
			<xs:element name="dataownercode" type="tmi8:dataownercodeType"/>
			<xs:element name="operationdate" type="tmi8:tmidateType"/>
			<xs:element name="lineplanningnumber" type="tmi8:lineplanningnumberType"/>
			<xs:element name="journeynumber" type="tmi8:journeynumberType"/>
			<xs:element name="reinforcementnumber" type="tmi8:fortifyordernumberType"/>
			<xs:element name="userstopcode" type="tmi8:codeType"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AllocationType">
		<xs:sequence>
			<xs:element name="allocationtime" type="tmi8:TimestampType"/>
			<xs:element name="sidecode" type="tmi8:sidecodeType"/>
			<xs:element name="quayid" type="tmi8:quayidType" minOccurs="0"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Message property types                                                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:group name="MessageProperties">
		<xs:sequence>
			<xs:element name="SubscriberID" type="tmi8:SubscriberIDType"/>
			<xs:element name="Version" type="tmi8:VersionType"/>
			<xs:element name="DossierName" type="tmi8:DossierNameType"/>
			<xs:element name="Timestamp" type="tmi8:TimestampType"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="DossierNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="KV5allocinfo"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VersionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SubscriberIDType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseCodeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="NOK"/>
			<xs:enumeration value="SE"/>
			<xs:enumeration value="NA"/>
			<xs:enumeration value="PE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResponseErrorType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Common entity types                                                               -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:simpleType name="dataownercodeType">
		<xs:annotation id="E1">
			<xs:documentation xml:lang="nl">
	Een en ander bepaalt volgens BISON enumeratie E1. 
	Op dit moment bekende waardes zijn: 
		Vervoerders: ARR, VTN, CXX, GVB, HTM, NS, RET, SYNTUS, QBUZZ, TCR, 
		Integrators:  ALGEMEEN, GOVI, RIG, SABIMOS, PRORAIL 
		maar elke waarde is toegestaan
	</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sidecodeType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="quayidType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidateType">
		<xs:annotation>
			<xs:documentation>Format: YYYY-MM-DD</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			<!--
			<xs:minLength value="10"/>
			<xs:maxLength value="10"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidatetimeType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!--  General BISON entity types                                                       -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:simpleType name="codeType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="fortifyordernumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="journeynumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lineplanningnumberType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="userstopordernumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</xs:schema>

=== BISONNL/KV5/xml/kv5example.xml
<?xml version="1.0" encoding="UTF-8"?>
<tmi8:DS_TM_PUSH xmlns:tmi8="http://bison.connekt.nl/tmi8/kv5/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv5/msg kv5-msg.xsd">
	<tmi8:SubscriberID>ABC1234</tmi8:SubscriberID>
	<tmi8:Version>8.1.1</tmi8:Version>
	<tmi8:DossierName>KV5allocinfo</tmi8:DossierName>
	<tmi8:Timestamp>2013-02-12T12:49:31</tmi8:Timestamp>
	<tmi8:KV5allocInfo>
		<tmi8:passage>
			<tmi8:dataownercode>ARR</tmi8:dataownercode>
			<tmi8:operationdate>2013-02-12</tmi8:operationdate>
			<tmi8:lineplanningnumber>N198</tmi8:lineplanningnumber>
			<tmi8:journeynumber>1021</tmi8:journeynumber>
			<tmi8:reinforcementnumber>0</tmi8:reinforcementnumber>
			<tmi8:userstopcode>57330090</tmi8:userstopcode>
		</tmi8:passage>
		<tmi8:allocation>
			<tmi8:allocationtime>2013-02-12T12:49:28</tmi8:allocationtime>
			<tmi8:sidecode>G</tmi8:sidecode>
		</tmi8:allocation>
	</tmi8:KV5allocInfo>
	<tmi8:KV5allocInfo>
		<tmi8:passage>
			<tmi8:dataownercode>CXX</tmi8:dataownercode>
			<tmi8:operationdate>2013-02-12</tmi8:operationdate>
			<tmi8:lineplanningnumber>61s</tmi8:lineplanningnumber>
			<tmi8:journeynumber>5555</tmi8:journeynumber>
			<tmi8:reinforcementnumber>1</tmi8:reinforcementnumber>
			<tmi8:userstopcode>57330088</tmi8:userstopcode>
		</tmi8:passage>
		<tmi8:allocation>
			<tmi8:allocationtime>2013-02-12T12:49:29</tmi8:allocationtime>
			<tmi8:sidecode>Perron B</tmi8:sidecode>
			<tmi8:quayid>CBSGM0014-12345</tmi8:quayid>
		</tmi8:allocation>
	</tmi8:KV5allocInfo>
</tmi8:DS_TM_PUSH>
